# shellcheck shell=bash

if ! declare -F _set_command_description >/dev/null 2>&1; then
  # Support direct sourcing of this command registry without requiring lib/cli.sh first.
  # shellcheck source=./_set_command_description.sh
  source "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/_set_command_description.sh"
fi

# Command descriptions (keep aligned with README summaries)
_set_command_description "start-nginx" "Start or recreate the Nginx proxy container (refreshes backend IPs)"
_set_command_description "stop-nginx" "Stop the Nginx proxy container without removing it"
_set_command_description "remove-nginx" "Remove the Nginx proxy container"
_set_command_description "status" "Show overall status, settings, headers, TLS overrides, and port mappings"
_set_command_description "status-all" "Show the full operator status report with certificates, paths, Docker opts, and diagnostics"
_set_command_description "fix-default-config" "Regenerate default Nginx config and certificates"
_set_command_description "update-nginx-config" "Regenerate config files without recreating the container (fails fast if nginx -s reload fails on a reused container)"
_set_command_description "fix-permissions" "Normalize repository permissions, or explicitly prepare Darwin Certbot mounts for sudo user mapping"

_set_command_description "list-backends" "Show configured backends with TLS/override details and port summary"
_set_command_description "add-backend" "Start a backend container and create the initial port mapping"
_set_command_description "remove-backend" "Remove a backend and its port mappings (--yes for scripts)"
_set_command_description "add-host-alias" "Add an alternate hostname that maps to an existing backend"
_set_command_description "remove-host-alias" "Remove a host alias for a backend"
_set_command_description "list-host-aliases" "List configured host aliases, optionally filtered by domain"
_set_command_description "add-dedicated-host" "Add a dedicated hostname with independent config (mTLS, ACL, headers)"
_set_command_description "remove-dedicated-host" "Remove a dedicated host"
_set_command_description "list-dedicated-hosts" "List configured dedicated hosts, optionally filtered by domain"
_set_command_description "set-dedicated-host-inherit" "Set inheritance for a dedicated host (mtls/acl/security_rules/headers/paths/all)"
_set_command_description "show-dedicated-host-inherit" "Show inheritance settings for a dedicated host"
_set_command_description "start-backend" "Start a backend container"
_set_command_description "stop-backend" "Stop a backend container"
_set_command_description "restart-backend" "Restart a backend container"
_set_command_description "update-backend" "Update backend image, container port, Docker options, or network"
_set_command_description "replace-backend-network" "Move a backend container to a different Docker network"
_set_command_description "add-port" "Add or expose an HTTP/HTTPS/TCP/UDP port for a backend"
_set_command_description "remove-port" "Remove a port mapping for a backend"
_set_command_description "update-port" "Update an existing port mapping, protocol, certificate, or HTTP/3 settings"
_set_command_description "enable-ws" "Mark a port mapping as a WebSocket endpoint"
_set_command_description "disable-ws" "Disable WebSocket handling for a port mapping"
_set_command_description "set-port-http3" "Enable or disable HTTP/3 for an HTTPS listen port"
_set_command_description "list-port-http3" "List HTTP/3 and Alt-Svc state for HTTPS ports"
_set_command_description "add-path-option" "Add advanced path routing overrides (match/priority/target/rewrite/metadata)"
_set_command_description "update-path-option" "Update advanced path routing overrides and metadata"
_set_command_description "remove-path-option" "Remove a specific path override"
_set_command_description "remove-all-path-options" "Remove path overrides (all or per backend)"
_set_command_description "list-path-options" "List path overrides for a backend and port"
_set_command_description "set-port-redirect" "Toggle HTTP→HTTPS redirect for a port with an optional status code"
_set_command_description "remove-port-redirect" "Disable HTTP→HTTPS redirect for a port"
_set_command_description "list-port-mappings" "List configured port mappings with WebSocket and redirect flags"
_set_command_description "set-port-tls-protocols" "Override TLS protocol versions for an HTTPS port"
_set_command_description "remove-port-tls-protocols" "Clear TLS protocol override for an HTTPS port"
_set_command_description "set-port-tls-ciphers" "Override TLS cipher string for an HTTPS port"
_set_command_description "remove-port-tls-ciphers" "Clear TLS cipher override for an HTTPS port"
_set_command_description "start-all-backends" "Start all backend containers"
_set_command_description "stop-all-backends" "Stop all backend containers"
_set_command_description "restart-all-backends" "Restart all backend containers"
_set_command_description "remove-all-backends" "Remove all backend containers and port mappings"

_set_command_description "add-cert" "Generate or upload a certificate for a domain and optional port suffix"
_set_command_description "replace-cert" "Regenerate or replace an existing certificate"
_set_command_description "list-certs" "List known certificate directories and mapped ports"
_set_command_description "renew-certs" "Renew expiring Let's Encrypt certificates and refresh config"
_set_command_description "remove-cert" "Delete a certificate directory for a domain or port suffix"

_set_command_description "clean-all" "Remove all references for a single domain"
_set_command_description "uninstall-all" "Uninstall by scope: backend state (default), full config, or full runtime"
_set_command_description "set-nginx-directive" "Set a typed nginx directive override (global/backend/port/path/stream scopes)"
_set_command_description "set-nginx-directive-raw" "Set a raw nginx directive override with safety validation"
_set_command_description "remove-nginx-directive" "Remove one nginx directive override by scope/target"
_set_command_description "remove-all-nginx-directives" "Remove nginx directive overrides (all or filtered by scope)"
_set_command_description "list-nginx-directives" "List nginx directive overrides with scope and mode"
_set_command_description "list-nginx-directive-catalog" "List supported typed directives and ownership"
_set_command_description "set-nginx-directive-strict" "Enable or disable strict ownership enforcement for directives"
_set_command_description "show-nginx-directive-strict" "Show strict ownership mode for nginx directives"

_set_command_description "add-backend-header" "Add a request or response header override for a backend"
_set_command_description "update-backend-header" "Update a backend header override"
_set_command_description "remove-backend-header" "Remove a backend header override"
_set_command_description "remove-all-backend-headers" "Remove all header overrides for a backend"
_set_command_description "list-backend-headers" "List header overrides for a backend"
_set_command_description "remove-all-headers" "Remove all global headers"
_set_command_description "set-backend-hsts" "Set or clear HSTS for a backend"
_set_command_description "set-backend-csp" "Set or clear a Content-Security-Policy for a backend"

_set_command_description "list-log-fields" "Show configured access log fields"
_set_command_description "add-log-field" "Add or insert an access log field"
_set_command_description "remove-log-field" "Remove an access log field by ID"
_set_command_description "update-log-field" "Update or replace an access log field by ID"
_set_command_description "move-log-field" "Reorder access log fields"

_set_command_description "set-backend-http-version" "Override HTTP version for one backend"
_set_command_description "remove-backend-http-version" "Clear HTTP version override for a backend"
_set_command_description "enable-backend-mtls" "Enable backend mTLS (mutual TLS) and optionally mint a client certificate"
_set_command_description "disable-backend-mtls" "Disable backend mTLS for a domain"
_set_command_description "add-backend-client-cert" "Generate a client certificate for backend mTLS"
_set_command_description "revoke-backend-client-cert" "Revoke a backend client certificate"
_set_command_description "remove-backend-client-cert" "Delete a backend client certificate"
_set_command_description "list-backend-client-certs" "List client certificates for a backend"
_set_command_description "replace-backend-client-cert" "Regenerate a backend client certificate"
_set_command_description "export-backend-client-p12" "Export a password-protected PKCS#12 for a backend client certificate"
_set_command_description "list-backend-cas" "List configured backend CAs"
_set_command_description "replace-backend-ca" "Recreate a backend mTLS CA and remove existing client certificates"
_set_command_description "remove-backend-ca" "Delete the backend CA and client certificates"
_set_command_description "set-backend-client-ip-header" "Override the client IP header for one backend"
_set_command_description "remove-backend-client-ip-header" "Clear client IP header override for a backend"
_set_command_description "set-backend-proxy-ip-header" "Override proxy IP header for one backend"
_set_command_description "remove-backend-proxy-ip-header" "Clear proxy IP header override for a backend"
_set_command_description "set-backend-acl-policy" "Override ACL allow/deny policy for one backend"
_set_command_description "remove-backend-acl-policy" "Clear backend ACL policy override"
_set_command_description "set-backend-acl-status" "Override ACL status code for one backend"
_set_command_description "remove-backend-acl-status" "Clear backend ACL status override"
_set_command_description "set-backend-security-rule-status" "Override security rule status code for one backend"
_set_command_description "remove-backend-security-rule-status" "Clear backend security rule status override"

_set_command_description "add-acl" "Add an IP ACL rule (L7, L3, or both) for a domain (HTTP + TCP)"
_set_command_description "remove-acl" "Remove an ACL rule by ID"
_set_command_description "disable-acl" "Disable an ACL rule"
_set_command_description "enable-acl" "Enable an ACL rule"
_set_command_description "disable-all-acl" "Disable all ACL rules"
_set_command_description "enable-all-acl" "Enable all ACL rules"
_set_command_description "remove-all-acl" "Remove all ACL rules"
_set_command_description "update-acl" "Update an ACL rule's domain, scope, action, or status"
_set_command_description "move-acl-rule" "Reorder ACL rules"
_set_command_description "list-acl" "List ACL rules and their order"
_set_command_description "add-security-rule" "Add a security rule with request attribute conditions"
_set_command_description "update-security-rule" "Update or replace a security rule"
_set_command_description "remove-security-rule" "Remove a security rule by ID"
_set_command_description "remove-all-security-rules" "Remove all security rules"
_set_command_description "disable-security-rule" "Disable a security rule"
_set_command_description "enable-security-rule" "Enable a security rule"
_set_command_description "disable-all-security-rules" "Disable all security rules"
_set_command_description "enable-all-security-rules" "Enable all security rules"
_set_command_description "move-security-rule" "Reorder security rules"
_set_command_description "set-security-rule-mode" "Set how multiple conditions are combined for new rules"
_set_command_description "duplicate-security-rule" "Duplicate a security rule"
_set_command_description "list-security-rules" "List security rules with domains and conditions"

_set_command_description "check-config" "Run nginx -t inside the proxy container"
_set_command_description "tail-proxy-logs" "Tail proxy access and error logs"

_set_command_description "help" "Show command-specific help topics"
_set_command_description "help-update" "Show the local release-tag update workflow"
_set_command_description "upgrade-preflight" "Read-only check for local state and optional release-tag compatibility"

_set_command_description "create-backup" "Create a configuration backup (optionally described)"
_set_command_description "list-backups" "List available backups"
_set_command_description "restore-backup" "Restore a backup directory or archive"

_set_command_description "control-server-tokens" "Toggle Nginx server_tokens globally"
_set_command_description "show-server-tokens" "Show the current server_tokens setting"
_set_command_description "set-client-ip-header" "Configure which client IP header to trust or disable"
_set_command_description "set-proxy-ip-header" "Set the header carrying the proxy IP address"
_set_command_description "add-header" "Add a global request or response header"
_set_command_description "update-header" "Update a global header value"
_set_command_description "remove-header" "Remove a global header"
_set_command_description "list-headers" "List configured global headers"
_set_command_description "set-hsts" "Set or disable global HSTS"
_set_command_description "set-csp" "Set or disable a global Content-Security-Policy"
_set_command_description "set-auto-backups" "Enable or disable automatic backups"
_set_command_description "set-backup-retention" "Set automatic backup retention in days"
_set_command_description "set-backup-compression" "Toggle compression for automatic backups"
_set_command_description "set-http-version" "Set the global HTTP version for proxying"
_set_command_description "set-tls-protocols" "Set global TLS protocol list for HTTPS listeners"
_set_command_description "set-tls-ciphers" "Set global TLS cipher string"
_set_command_description "set-security-rule-status" "Set the global status code for security rule violations"
_set_command_description "set-acl-status" "Set the global status code for ACL denials"
_set_command_description "set-acl-policy" "Set the global ACL allow/deny policy"
_set_command_description "set-trusted-proxies" "Define trusted proxy CIDRs for client IP headers"
_set_command_description "set-real-ip-recursive" "Toggle recursive real_ip processing"
_set_command_description "set-nginx-docker-opts" "Set persistent docker run options for the Nginx proxy container"
_set_command_description "show-nginx-docker-opts" "Show persistent docker run options for the Nginx proxy container"
_set_command_description "set-visibility-policy" "Choose full or redacted display/history/audit for operator values"
_set_command_description "show-visibility-policy" "Show the current operator value visibility policy"
_set_command_description "set-nginx-image" "Persist the Nginx image used for the proxy container"
_set_command_description "set-certbot-image" "Choose the Certbot image used for ACME issuance"

_set_command_description "start-capture" "Start packet capture in the proxy container (optional TLS decrypt mode)"
_set_command_description "stop-capture" "Stop an active packet capture"
