#! /bin/sh
# vim:et:ft=sh:sts=2:sw=2
#
# Copyright 2008-2020 Kate Ward. All Rights Reserved.
# Released under the Apache 2.0 license.
# http://www.apache.org/licenses/LICENSE-2.0
#
# shUnit2 -- Unit testing framework for Unix shell scripts.
# https://github.com/kward/shunit2
#
# Author: kate.ward@forestent.com (Kate Ward)
#
# shUnit2 is a xUnit based unit test framework for Bourne shell scripts. It is
# based on the popular JUnit unit testing framework for Java.
#
# $() are not fully portable (POSIX != portable).
#   shellcheck disable=SC2006
# expr may be antiquated, but it is the only solution in some cases.
#   shellcheck disable=SC2003

__SHUNIT2_DIR=`dirname "${SHUNIT2:-$0}"`
__SHUNIT2_DIR=`cd "${__SHUNIT2_DIR}" >/dev/null 2>&1 && pwd`

# Return if shunit2 already loaded.
command [ -n "${SHUNIT_VERSION:-}" ] && exit 0
SHUNIT_VERSION='2.1.8'

# Return values that scripts can use.
SHUNIT_TRUE=0
SHUNIT_FALSE=1
SHUNIT_ERROR=2

# Logging functions.
# shellcheck disable=SC1090
. "${__SHUNIT2_DIR}/shunit2.d/_shunit_warn.sh"
# shellcheck disable=SC1090
. "${__SHUNIT2_DIR}/shunit2.d/_shunit_error.sh"
# shellcheck disable=SC1090
. "${__SHUNIT2_DIR}/shunit2.d/_shunit_fatal.sh"

# Determine some reasonable command defaults.
__SHUNIT_CMD_ECHO_ESC='echo -e'
# shellcheck disable=SC2039
command [ "`echo -e test`" = '-e test' ] && __SHUNIT_CMD_ECHO_ESC='echo'

__SHUNIT_UNAME_S=`uname -s`
case "${__SHUNIT_UNAME_S}" in
  BSD) __SHUNIT_CMD_EXPR='gexpr' ;;
  *) __SHUNIT_CMD_EXPR='expr' ;;
esac
__SHUNIT_CMD_TPUT='tput'

# Commands a user can override if needed.
SHUNIT_CMD_EXPR=${SHUNIT_CMD_EXPR:-${__SHUNIT_CMD_EXPR}}
SHUNIT_CMD_TPUT=${SHUNIT_CMD_TPUT:-${__SHUNIT_CMD_TPUT}}

# Enable color output. Options are 'never', 'always', or 'auto'.
SHUNIT_COLOR=${SHUNIT_COLOR:-auto}

# Specific shell checks.
if command [ -n "${ZSH_VERSION:-}" ]; then
  setopt |grep "^shwordsplit$" >/dev/null
  if command [ $? -ne ${SHUNIT_TRUE} ]; then
    _shunit_fatal 'zsh shwordsplit option is required for proper operation'
  fi
  if command [ -z "${SHUNIT_PARENT:-}" ]; then
    _shunit_fatal "zsh does not pass \$0 through properly. please declare \
\"SHUNIT_PARENT=\$0\" before calling shUnit2"
  fi
fi

#
# Constants
#

__SHUNIT_MODE_SOURCED='sourced'
__SHUNIT_MODE_STANDALONE='standalone'
__SHUNIT_PARENT=${SHUNIT_PARENT:-$0}

# User provided test prefix to display in front of the name of the test being
# executed. Define by setting the SHUNIT_TEST_PREFIX variable.
__SHUNIT_TEST_PREFIX=${SHUNIT_TEST_PREFIX:-}

# ANSI colors.
__SHUNIT_ANSI_NONE='\033[0m'
__SHUNIT_ANSI_RED='\033[1;31m'
__SHUNIT_ANSI_GREEN='\033[1;32m'
__SHUNIT_ANSI_YELLOW='\033[1;33m'
__SHUNIT_ANSI_CYAN='\033[1;36m'

# Set the constants readonly.
__shunit_constants=`set |grep '^__SHUNIT_' |cut -d= -f1`
echo "${__shunit_constants}" |grep '^Binary file' >/dev/null && \
    __shunit_constants=`set |grep -a '^__SHUNIT_' |cut -d= -f1`
for __shunit_const in ${__shunit_constants}; do
  if command [ -z "${ZSH_VERSION:-}" ]; then
    readonly "${__shunit_const}"
  else
    case ${ZSH_VERSION} in
      [123].*) readonly "${__shunit_const}" ;;
      *) readonly -g "${__shunit_const}"  # Declare readonly constants globally.
    esac
  fi
done
unset __shunit_const __shunit_constants

#
# Internal variables.
#

# Variables.
__shunit_lineno=''  # Line number of executed test.
__shunit_mode=${__SHUNIT_MODE_SOURCED}  # Operating mode.
__shunit_reportGenerated=${SHUNIT_FALSE}  # Is report generated.
__shunit_script=''  # Filename of unittest script (standalone mode).
__shunit_skip=${SHUNIT_FALSE}  # Is skipping enabled.
__shunit_suite=''  # Suite of tests to execute.
__shunit_clean=${SHUNIT_FALSE}  # _shunit_cleanup() was already called.

# ANSI colors (populated by _shunit_configureColor()).
__shunit_ansi_none=''
__shunit_ansi_red=''
__shunit_ansi_green=''
__shunit_ansi_yellow=''
__shunit_ansi_cyan=''

# Counts of tests.
__shunit_testSuccess=${SHUNIT_TRUE}
__shunit_testsTotal=0
__shunit_testsPassed=0
__shunit_testsFailed=0

# Counts of asserts.
__shunit_assertsTotal=0
__shunit_assertsPassed=0
__shunit_assertsFailed=0
__shunit_assertsSkipped=0

#
# Macros.
#

# shellcheck disable=SC2016,SC2089
_SHUNIT_LINENO_='eval __shunit_lineno=""; if command [ "${1:-}" = "--lineno" ]; then command [ -n "$2" ] && __shunit_lineno="[$2] "; shift 2; fi'

#-----------------------------------------------------------------------------
# Assertion functions.
#

# Assert that two values are equal to one another.
#
# Args:
#   message: string: failure message [optional]
#   expected: string: expected value
#   actual: string: actual value
# Returns:
#   integer: success (TRUE/FALSE/ERROR constant)
# shellcheck disable=SC1090
. "${__SHUNIT2_DIR}/shunit2.d/assertEquals.sh"
# shellcheck disable=SC2016,SC2034
_ASSERT_EQUALS_='eval assertEquals --lineno "${LINENO:-}"'

# Assert that two values are not equal to one another.
#
# Args:
#   message: string: failure message [optional]
#   expected: string: expected value
#   actual: string: actual value
# Returns:
#   integer: success (TRUE/FALSE/ERROR constant)
# shellcheck disable=SC1090
. "${__SHUNIT2_DIR}/shunit2.d/assertNotEquals.sh"
# shellcheck disable=SC2016,SC2034
_ASSERT_NOT_EQUALS_='eval assertNotEquals --lineno "${LINENO:-}"'

# Assert that a container contains a content.
#
# Args:
#   message: string: failure message [optional]
#   container: string: container to analyze
#   content: string: content to find
# Returns:
#   integer: success (TRUE/FALSE/ERROR constant)
# shellcheck disable=SC1090
. "${__SHUNIT2_DIR}/shunit2.d/assertContains.sh"
# shellcheck disable=SC2016,SC2034
_ASSERT_CONTAINS_='eval assertContains --lineno "${LINENO:-}"'

# Assert that a container does not contain a content.
#
# Args:
#   message: string: failure message [optional]
#   container: string: container to analyze
#   content: string: content to look for
# Returns:
#   integer: success (TRUE/FALSE/ERROR constant)
# shellcheck disable=SC1090
. "${__SHUNIT2_DIR}/shunit2.d/assertNotContains.sh"
# shellcheck disable=SC2016,SC2034
_ASSERT_NOT_CONTAINS_='eval assertNotContains --lineno "${LINENO:-}"'

# Assert that a value is null (i.e. an empty string)
#
# Args:
#   message: string: failure message [optional]
#   actual: string: actual value
# Returns:
#   integer: success (TRUE/FALSE/ERROR constant)
# shellcheck disable=SC1090
. "${__SHUNIT2_DIR}/shunit2.d/assertNull.sh"
# shellcheck disable=SC2016,SC2034
_ASSERT_NULL_='eval assertNull --lineno "${LINENO:-}"'

# Assert that a value is not null (i.e. a non-empty string)
#
# Args:
#   message: string: failure message [optional]
#   actual: string: actual value
# Returns:
#   integer: success (TRUE/FALSE/ERROR constant)
# shellcheck disable=SC1090
. "${__SHUNIT2_DIR}/shunit2.d/assertNotNull.sh"
# shellcheck disable=SC2016,SC2034
_ASSERT_NOT_NULL_='eval assertNotNull --lineno "${LINENO:-}"'

# Assert that two values are the same (i.e. equal to one another).
#
# Args:
#   message: string: failure message [optional]
#   expected: string: expected value
#   actual: string: actual value
# Returns:
#   integer: success (TRUE/FALSE/ERROR constant)
# shellcheck disable=SC1090
. "${__SHUNIT2_DIR}/shunit2.d/assertSame.sh"
# shellcheck disable=SC2016,SC2034
_ASSERT_SAME_='eval assertSame --lineno "${LINENO:-}"'

# Assert that two values are not the same (i.e. not equal to one another).
#
# Args:
#   message: string: failure message [optional]
#   expected: string: expected value
#   actual: string: actual value
# Returns:
#   integer: success (TRUE/FALSE/ERROR constant)
# shellcheck disable=SC1090
. "${__SHUNIT2_DIR}/shunit2.d/assertNotSame.sh"
# shellcheck disable=SC2016,SC2034
_ASSERT_NOT_SAME_='eval assertNotSame --lineno "${LINENO:-}"'

# Assert that a value or shell test condition is true.
#
# In shell, a value of 0 is true and a non-zero value is false. Any integer
# value passed can thereby be tested.
#
# Shell supports much more complicated tests though, and a means to support
# them was needed. As such, this function tests that conditions are true or
# false through evaluation rather than just looking for a true or false.
#
# The following test will succeed:
#   assertTrue 0
#   assertTrue "[ 34 -gt 23 ]"
# The following test will fail with a message:
#   assertTrue 123
#   assertTrue "test failed" "[ -r '/non/existent/file' ]"
#
# Args:
#   message: string: failure message [optional]
#   condition: string: integer value or shell conditional statement
# Returns:
#   integer: success (TRUE/FALSE/ERROR constant)
# shellcheck disable=SC1090
. "${__SHUNIT2_DIR}/shunit2.d/assertTrue.sh"
# shellcheck disable=SC2016,SC2034
_ASSERT_TRUE_='eval assertTrue --lineno "${LINENO:-}"'

# Assert that a value or shell test condition is false.
#
# In shell, a value of 0 is true and a non-zero value is false. Any integer
# value passed can thereby be tested.
#
# Shell supports much more complicated tests though, and a means to support
# them was needed. As such, this function tests that conditions are true or
# false through evaluation rather than just looking for a true or false.
#
# The following test will succeed:
#   assertFalse 1
#   assertFalse "[ 'apples' = 'oranges' ]"
# The following test will fail with a message:
#   assertFalse 0
#   assertFalse "test failed" "[ 1 -eq 1 -a 2 -eq 2 ]"
#
# Args:
#   message: string: failure message [optional]
#   condition: string: integer value or shell conditional statement
# Returns:
#   integer: success (TRUE/FALSE/ERROR constant)
# shellcheck disable=SC1090
. "${__SHUNIT2_DIR}/shunit2.d/assertFalse.sh"
# shellcheck disable=SC2016,SC2034
_ASSERT_FALSE_='eval assertFalse --lineno "${LINENO:-}"'

#-----------------------------------------------------------------------------
# Failure functions.
#

# Records a test failure.
#
# Args:
#   message: string: failure message [optional]
# Returns:
#   integer: success (TRUE/FALSE/ERROR constant)
# shellcheck disable=SC1090
. "${__SHUNIT2_DIR}/shunit2.d/fail.sh"
# shellcheck disable=SC2016,SC2034
_FAIL_='eval fail --lineno "${LINENO:-}"'

# Records a test failure, stating two values were not equal.
#
# Args:
#   message: string: failure message [optional]
#   expected: string: expected value
#   actual: string: actual value
# Returns:
#   integer: success (TRUE/FALSE/ERROR constant)
# shellcheck disable=SC1090
. "${__SHUNIT2_DIR}/shunit2.d/failNotEquals.sh"
# shellcheck disable=SC2016,SC2034
_FAIL_NOT_EQUALS_='eval failNotEquals --lineno "${LINENO:-}"'

# Records a test failure, stating a value was found.
#
# Args:
#   message: string: failure message [optional]
#   content: string: found value
# Returns:
#   integer: success (TRUE/FALSE/ERROR constant)
# shellcheck disable=SC1090
. "${__SHUNIT2_DIR}/shunit2.d/failFound.sh"
# shellcheck disable=SC2016,SC2034
_FAIL_FOUND_='eval failFound --lineno "${LINENO:-}"'

# Records a test failure, stating a content was not found.
#
# Args:
#   message: string: failure message [optional]
#   content: string: content not found
# Returns:
#   integer: success (TRUE/FALSE/ERROR constant)
# shellcheck disable=SC1090
. "${__SHUNIT2_DIR}/shunit2.d/failNotFound.sh"
# shellcheck disable=SC2016,SC2034
_FAIL_NOT_FOUND_='eval failNotFound --lineno "${LINENO:-}"'

# Records a test failure, stating two values should have been the same.
#
# Args:
#   message: string: failure message [optional]
#   expected: string: expected value
#   actual: string: actual value
# Returns:
#   integer: success (TRUE/FALSE/ERROR constant)
failSame()
{
  # shellcheck disable=SC2090
  ${_SHUNIT_LINENO_}
  if command [ $# -lt 2 -o $# -gt 3 ]; then
    _shunit_error "failSame() requires two or three arguments; $# given"
    return ${SHUNIT_ERROR}
  fi
  _shunit_shouldSkip && return ${SHUNIT_TRUE}

  shunit_message_=${__shunit_lineno}
  if command [ $# -eq 3 ]; then
    shunit_message_="${shunit_message_}$1"
    shift
  fi

  shunit_message_=${shunit_message_%% }
  _shunit_assertFail "${shunit_message_:+${shunit_message_} }expected not same"

  unset shunit_message_
  return ${SHUNIT_FALSE}
}
# shellcheck disable=SC2016,SC2034
_FAIL_SAME_='eval failSame --lineno "${LINENO:-}"'

# Records a test failure, stating two values were not equal.
#
# This is functionally equivalent to calling failNotEquals().
#
# Args:
#   message: string: failure message [optional]
#   expected: string: expected value
#   actual: string: actual value
# Returns:
#   integer: success (TRUE/FALSE/ERROR constant)
# shellcheck disable=SC1090
. "${__SHUNIT2_DIR}/shunit2.d/failNotSame.sh"
# shellcheck disable=SC2016,SC2034
_FAIL_NOT_SAME_='eval failNotSame --lineno "${LINENO:-}"'

#-----------------------------------------------------------------------------
# Skipping functions.
#

# Force remaining assert and fail functions to be "skipped".
#
# This function forces the remaining assert and fail functions to be "skipped",
# i.e. they will have no effect. Each function skipped will be recorded so that
# the total of asserts and fails will not be altered.
#
# Args:
#   None
# shellcheck disable=SC1090
. "${__SHUNIT2_DIR}/shunit2.d/startSkipping.sh"
# shellcheck disable=SC1090
. "${__SHUNIT2_DIR}/shunit2.d/endSkipping.sh"
# shellcheck disable=SC1090
. "${__SHUNIT2_DIR}/shunit2.d/isSkipping.sh"
# shellcheck disable=SC1090
. "${__SHUNIT2_DIR}/shunit2.d/suite_addTest.sh"

# Stub. This function will be called once before any tests are run.
#
# Common one-time environment preparation tasks shared by all tests can be
# defined here.
#
# This function should be overridden by the user in their unit test suite.
# Note: see _shunit_mktempFunc() for actual implementation
#
# Args:
#   None
#oneTimeSetUp() { :; }  # DO NOT UNCOMMENT THIS FUNCTION

# Stub. This function will be called once after all tests are finished.
#
# Common one-time environment cleanup tasks shared by all tests can be defined
# here.
#
# This function should be overridden by the user in their unit test suite.
# Note: see _shunit_mktempFunc() for actual implementation
#
# Args:
#   None
#oneTimeTearDown() { :; }  # DO NOT UNCOMMENT THIS FUNCTION

# Stub. This function will be called before each test is run.
#
# Common environment preparation tasks shared by all tests can be defined here.
#
# This function should be overridden by the user in their unit test suite.
# Note: see _shunit_mktempFunc() for actual implementation
#
# Args:
#   None
#setUp() { :; }  # DO NOT UNCOMMENT THIS FUNCTION

# Note: see _shunit_mktempFunc() for actual implementation
# Stub. This function will be called after each test is run.
#
# Common environment cleanup tasks shared by all tests can be defined here.
#
# This function should be overridden by the user in their unit test suite.
# Note: see _shunit_mktempFunc() for actual implementation
#
# Args:
#   None
#tearDown() { :; }  # DO NOT UNCOMMENT THIS FUNCTION

#------------------------------------------------------------------------------
# Internal shUnit2 functions.
#

# Create a temporary directory to store various run-time files in.
#
# This function is a cross-platform temporary directory creation tool. Not all
# OSes have the `mktemp` function, so one is included here.
#
# Args:
#   None
# Outputs:
#   string: the temporary directory that was created
# shellcheck disable=SC1090
. "${__SHUNIT2_DIR}/shunit2.d/_shunit_mktempDir.sh"

# This function is here to work around issues in Cygwin.
#
# Args:
#   None
# shellcheck disable=SC1090
. "${__SHUNIT2_DIR}/shunit2.d/_shunit_mktempFunc.sh"

# Final cleanup function to leave things as we found them.
#
# Besides removing the temporary directory, this function is in charge of the
# final exit code of the unit test. The exit code is based on how the script
# was ended (e.g. normal exit, or via Ctrl-C).
#
# Args:
#   name: string: name of the trap called (specified when trap defined)
# shellcheck disable=SC1090
. "${__SHUNIT2_DIR}/shunit2.d/_shunit_cleanup.sh"

# configureColor based on user color preference.
#
# Args:
#   color: string: color mode (one of `always`, `auto`, or `none`).
# shellcheck disable=SC1090
. "${__SHUNIT2_DIR}/shunit2.d/_shunit_configureColor.sh"

# colors returns the number of supported colors for the TERM.
# shellcheck disable=SC1090
. "${__SHUNIT2_DIR}/shunit2.d/_shunit_colors.sh"

# The actual running of the tests happens here.
#
# Args:
#   None
# shellcheck disable=SC1090
. "${__SHUNIT2_DIR}/shunit2.d/_shunit_execSuite.sh"

# Generates the user friendly report with appropriate OK/FAILED message.
#
# Args:
#   None
# Output:
#   string: the report of successful and failed tests, as well as totals.
# shellcheck disable=SC1090
. "${__SHUNIT2_DIR}/shunit2.d/_shunit_generateReport.sh"

# Test for whether a function should be skipped.
#
# Args:
#   None
# Returns:
#   boolean: whether the test should be skipped (TRUE/FALSE constant)
# shellcheck disable=SC1090
. "${__SHUNIT2_DIR}/shunit2.d/_shunit_shouldSkip.sh"

# Records a successful test.
#
# Args:
#   None
# shellcheck disable=SC1090
. "${__SHUNIT2_DIR}/shunit2.d/_shunit_assertPass.sh"

# Records a test failure.
#
# Args:
#   message: string: failure message to provide user
# shellcheck disable=SC1090
. "${__SHUNIT2_DIR}/shunit2.d/_shunit_assertFail.sh"

# Increment the count of failed asserts.
#
# Args:
#   none
# shellcheck disable=SC1090
. "${__SHUNIT2_DIR}/shunit2.d/_shunit_incFailedCount.sh"


# Records a skipped test.
#
# Args:
#   None
# shellcheck disable=SC1090
. "${__SHUNIT2_DIR}/shunit2.d/_shunit_assertSkip.sh"

# Prepare a script filename for sourcing.
#
# Args:
#   script: string: path to a script to source
# Returns:
#   string: filename prefixed with ./ (if necessary)
# shellcheck disable=SC1090
. "${__SHUNIT2_DIR}/shunit2.d/_shunit_prepForSourcing.sh"

# Escape a character in a string.
#
# Args:
#   c: string: unescaped character
#   s: string: to escape character in
# Returns:
#   string: with escaped character(s)
# shellcheck disable=SC1090
. "${__SHUNIT2_DIR}/shunit2.d/_shunit_escapeCharInStr.sh"

# Escape a character in a string.
#
# Args:
#   str: string: to escape characters in
# Returns:
#   string: with escaped character(s)
# shellcheck disable=SC1090
. "${__SHUNIT2_DIR}/shunit2.d/_shunit_escapeCharactersInString.sh"

# Extract list of functions to run tests against.
#
# Args:
#   script: string: name of script to extract functions from
# Returns:
#   string: of function names
# shellcheck disable=SC1090
. "${__SHUNIT2_DIR}/shunit2.d/_shunit_extractTestFunctions.sh"

#------------------------------------------------------------------------------
# Main.
#

# Determine the operating mode.
if command [ $# -eq 0 -o "${1:-}" = '--' ]; then
  __shunit_script=${__SHUNIT_PARENT}
  __shunit_mode=${__SHUNIT_MODE_SOURCED}
else
  __shunit_script=$1
  command [ -r "${__shunit_script}" ] || \
      _shunit_fatal "unable to read from ${__shunit_script}"
  __shunit_mode=${__SHUNIT_MODE_STANDALONE}
fi

# Create a temporary storage location.
__shunit_tmpDir=`_shunit_mktempDir`

# Provide a public temporary directory for unit test scripts.
# TODO(kward): document this.
SHUNIT_TMPDIR="${__shunit_tmpDir}/tmp"
command mkdir "${SHUNIT_TMPDIR}"

# Setup traps to clean up after ourselves.
trap '_shunit_cleanup EXIT' 0
trap '_shunit_cleanup INT' 2
trap '_shunit_cleanup TERM' 15

# Create phantom functions to work around issues with Cygwin.
_shunit_mktempFunc
PATH="${__shunit_tmpDir}:${PATH}"

# Make sure phantom functions are executable. This will bite if `/tmp` (or the
# current `$TMPDIR`) points to a path on a partition that was mounted with the
# 'noexec' option. The noexec command was created with `_shunit_mktempFunc()`.
noexec 2>/dev/null || _shunit_fatal \
    'Please declare TMPDIR with path on partition with exec permission.'

# We must manually source the tests in standalone mode.
if command [ "${__shunit_mode}" = "${__SHUNIT_MODE_STANDALONE}" ]; then
  # shellcheck disable=SC1090
  command . "`_shunit_prepForSourcing \"${__shunit_script}\"`"
fi

# Configure default output coloring behavior.
_shunit_configureColor "${SHUNIT_COLOR}"

# Execute the oneTimeSetUp function (if it exists).
oneTimeSetUp
command [ $? -eq ${SHUNIT_TRUE} ] \
    || _shunit_fatal "oneTimeSetUp() returned non-zero return code."

# Command line selected tests or suite selected tests
if command [ "$#" -ge 2 ]; then
  # Argument $1 is either the filename of tests or '--'; either way, skip it.
  shift
  # Remaining arguments ($2 .. $#) are assumed to be test function names.
  # Interate through all remaining args in "$@" in a POSIX (likely portable) way.
  # Helpful tip: https://unix.stackexchange.com/questions/314032/how-to-use-arguments-like-1-2-in-a-for-loop
  for _shunit_arg_ do
    suite_addTest "${_shunit_arg_}"
  done
  unset _shunit_arg_
else
  # Execute the suite function defined in the parent test script.
  # DEPRECATED as of 2.1.0.
  suite
fi

# If no tests or suite specified, dynamically build a list of functions.
if command [ -z "${__shunit_suite}" ]; then
  shunit_funcs_=`_shunit_extractTestFunctions "${__shunit_script}"`
  for shunit_func_ in ${shunit_funcs_}; do
    suite_addTest "${shunit_func_}"
  done
fi
unset shunit_func_ shunit_funcs_

# Execute the suite of unit tests.
_shunit_execSuite

# Execute the oneTimeTearDown function (if it exists).
oneTimeTearDown
command [ $? -eq ${SHUNIT_TRUE} ] \
    || _shunit_fatal "oneTimeTearDown() returned non-zero return code."

# Generate a report summary.
_shunit_generateReport

# That's it folks.
command [ "${__shunit_testsFailed}" -eq 0 ]
exit $?
