#define _GNU_SOURCE

#include <dlfcn.h>
#include <errno.h>
#include <fcntl.h>
#include <pthread.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/stat.h>
#include <sys/types.h>
#include <unistd.h>

#define HEADER "# SSL key log file generated by sslkeylogfile.c\n"
#define FILENAME_ENVVAR "LIBSSL_SSLKEYLOGFILE"

typedef struct ssl_st SSL;
typedef struct ssl_ctx_st SSL_CTX;

typedef void (*ssl_keylog_cb_fn)(const SSL *ssl, const char *line);
typedef SSL *(*ssl_new_fn)(SSL_CTX *ctx);
typedef void (*ssl_ctx_set_keylog_callback_fn)(SSL_CTX *ctx, ssl_keylog_cb_fn cb);

static pthread_once_t resolve_symbols_once = PTHREAD_ONCE_INIT;
static pthread_mutex_t keylog_mutex = PTHREAD_MUTEX_INITIALIZER;
static ssl_new_fn real_SSL_new = NULL;
static ssl_ctx_set_keylog_callback_fn real_SSL_CTX_set_keylog_callback = NULL;
static int fd_sslkeylogfile = -1;
static int keylog_disabled = 0;
static int keylog_warning_emitted = 0;
static char ssl_new_lookup_error[512] = "";

static void resolve_symbols(void);
static void resolve_ssl_new_from_handle(void *handle, const char *source, int special_handle);
static void warn_keylog_disabled_locked(const char *message);
static int open_sslkeylogfile_locked(void);
static void write_sslkeylogfile(const SSL *ssl, const char *line);

SSL *SSL_new(SSL_CTX *ctx) {
  pthread_once(&resolve_symbols_once, resolve_symbols);

  if (real_SSL_new == NULL) {
    fprintf(stderr, "TLS keylog helper fatal: could not resolve real SSL_new: %s\n",
      ssl_new_lookup_error[0] != '\0' ? ssl_new_lookup_error : "unknown lookup error");
    fflush(stderr);
    _exit(127);
  }

  if (real_SSL_CTX_set_keylog_callback != NULL) {
    real_SSL_CTX_set_keylog_callback(ctx, write_sslkeylogfile);
  }

  return real_SSL_new(ctx);
}

static void resolve_symbols(void) {
  const char *lookup_error = NULL;

  dlerror();
  real_SSL_new = (ssl_new_fn)dlsym(RTLD_NEXT, "SSL_new");
  lookup_error = dlerror();
  if (lookup_error != NULL) {
    snprintf(ssl_new_lookup_error, sizeof(ssl_new_lookup_error), "RTLD_NEXT SSL_new lookup failed: %s",
      lookup_error);
    real_SSL_new = NULL;
  } else if (real_SSL_new == SSL_new) {
    snprintf(ssl_new_lookup_error, sizeof(ssl_new_lookup_error),
      "RTLD_NEXT SSL_new lookup resolved to the keylog helper itself");
    real_SSL_new = NULL;
  }

  if (real_SSL_new == NULL) {
    resolve_ssl_new_from_handle(RTLD_DEFAULT, "RTLD_DEFAULT", 1);
  }
  if (real_SSL_new == NULL) {
    resolve_ssl_new_from_handle(dlopen("libssl.so.3", RTLD_NOW | RTLD_LOCAL), "libssl.so.3", 0);
  }
  if (real_SSL_new == NULL) {
    resolve_ssl_new_from_handle(dlopen("libssl.so.1.1", RTLD_NOW | RTLD_LOCAL), "libssl.so.1.1", 0);
  }
  if (real_SSL_new == NULL) {
    resolve_ssl_new_from_handle(dlopen("libssl.so", RTLD_NOW | RTLD_LOCAL), "libssl.so", 0);
  }

  dlerror();
  real_SSL_CTX_set_keylog_callback =
    (ssl_ctx_set_keylog_callback_fn)dlsym(RTLD_NEXT, "SSL_CTX_set_keylog_callback");
}

static void resolve_ssl_new_from_handle(void *handle, const char *source, int special_handle) {
  ssl_new_fn candidate = NULL;
  const char *lookup_error = NULL;

  if (handle == NULL && !special_handle) {
    lookup_error = dlerror();
    if (lookup_error != NULL) {
      snprintf(ssl_new_lookup_error, sizeof(ssl_new_lookup_error), "%s handle lookup failed: %s", source,
        lookup_error);
    }
    return;
  }

  dlerror();
  candidate = (ssl_new_fn)dlsym(handle, "SSL_new");
  lookup_error = dlerror();
  if (lookup_error != NULL || candidate == NULL) {
    snprintf(ssl_new_lookup_error, sizeof(ssl_new_lookup_error), "%s SSL_new lookup failed: %s", source,
      lookup_error != NULL ? lookup_error : "symbol not found");
    return;
  }
  if (candidate == SSL_new) {
    snprintf(ssl_new_lookup_error, sizeof(ssl_new_lookup_error),
      "%s SSL_new lookup resolved to the keylog helper itself", source);
    return;
  }

  real_SSL_new = candidate;
  ssl_new_lookup_error[0] = '\0';
}

static void warn_keylog_disabled_locked(const char *message) {
  if (!keylog_warning_emitted) {
    fprintf(stderr, "TLS keylog helper disabled: %s\n", message);
    keylog_warning_emitted = 1;
  }
}

static int open_sslkeylogfile_locked(void) {
  const char *filename = NULL;
  char message[512];

  if (fd_sslkeylogfile != -1) {
    return 1;
  }
  if (keylog_disabled) {
    return 0;
  }

  filename = getenv(FILENAME_ENVVAR);
  if (filename == NULL || *filename == '\0') {
    filename = getenv("SSLKEYLOGFILE");
  }

  if (filename == NULL || *filename == '\0') {
    keylog_disabled = 1;
    warn_keylog_disabled_locked("neither LIBSSL_SSLKEYLOGFILE nor SSLKEYLOGFILE is set");
    return 0;
  }

  fd_sslkeylogfile = open(filename, O_WRONLY | O_APPEND | O_CREAT, S_IRUSR | S_IWUSR);
  if (fd_sslkeylogfile == -1) {
    keylog_disabled = 1;
    snprintf(message, sizeof(message), "failed to open %s: %s", filename, strerror(errno));
    warn_keylog_disabled_locked(message);
    return 0;
  }

  if (lseek(fd_sslkeylogfile, 0, SEEK_END) == 0) {
    if (write(fd_sslkeylogfile, HEADER, sizeof(HEADER) - 1) < 0) {
      close(fd_sslkeylogfile);
      fd_sslkeylogfile = -1;
      keylog_disabled = 1;
      snprintf(message, sizeof(message), "failed to write header to %s: %s", filename, strerror(errno));
      warn_keylog_disabled_locked(message);
      return 0;
    }
  }

  return 1;
}

static void write_sslkeylogfile(const SSL *ssl, const char *line) {
  char message[512];
  char *record = NULL;
  size_t line_len = 0;
  size_t record_len = 0;
  ssize_t written = 0;
  int saved_errno = 0;
  (void)ssl;

  pthread_mutex_lock(&keylog_mutex);
  if (open_sslkeylogfile_locked()) {
    line_len = strlen(line);
    if (line_len > ((size_t)-1) - 1) {
      close(fd_sslkeylogfile);
      fd_sslkeylogfile = -1;
      keylog_disabled = 1;
      warn_keylog_disabled_locked("failed to write key material: keylog line is too large");
      pthread_mutex_unlock(&keylog_mutex);
      return;
    }

    record_len = line_len + 1;
    record = (char *)malloc(record_len);
    if (record == NULL) {
      saved_errno = errno;
      close(fd_sslkeylogfile);
      fd_sslkeylogfile = -1;
      keylog_disabled = 1;
      snprintf(message, sizeof(message), "failed to allocate keylog record buffer: %s",
        saved_errno != 0 ? strerror(saved_errno) : "out of memory");
      warn_keylog_disabled_locked(message);
      pthread_mutex_unlock(&keylog_mutex);
      return;
    }

    memcpy(record, line, line_len);
    record[line_len] = '\n';
    written = write(fd_sslkeylogfile, record, record_len);
    saved_errno = errno;
    free(record);
    if (written < 0) {
      close(fd_sslkeylogfile);
      fd_sslkeylogfile = -1;
      keylog_disabled = 1;
      snprintf(message, sizeof(message), "failed to write key material: %s", strerror(saved_errno));
      warn_keylog_disabled_locked(message);
    } else if ((size_t)written != record_len) {
      close(fd_sslkeylogfile);
      fd_sslkeylogfile = -1;
      keylog_disabled = 1;
      snprintf(message, sizeof(message), "failed to write key material: short write (%ld of %lu bytes)",
        (long)written, (unsigned long)record_len);
      warn_keylog_disabled_locked(message);
    }
  }
  pthread_mutex_unlock(&keylog_mutex);
}
